FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

RUN install_packages build-essential curl file libglib2.0-dev gobject-introspection libgirepository1.0-dev python3-gi

ENV PATH=/root/.cargo/bin:$PATH

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

WORKDIR /app

COPY . .

RUN make

RUN strip target/release/fin

RUN strip target/release/libfin.so

CMD ["sleep", "infinity"]
